version: "3.7"
services:
  jekyll:
    build: .
    command: jekyll serve --force_polling --config _config.yml,_config-dev.yml
    ports:
    - "4000:4000"
    volumes:
    - .:/srv/jekyll
    environment:
    - JEKYLL_ENV=dev
